### ISSUE TITLE
JsonException only since php 7.3

### ISSUE THREAD

**Issue by anikeevda** [elegant-bro/stringify#1]
in JsonEncoded class using JsonException [will throw ](https://www.php.net/manual/ru/class.jsonexception.php) an error on php < 7.3.0 because at composer.json platform is 7.1

There are special option for throwing error - JSON_THROW_ON_ERROR  - also since php 7.3.0

```php
public function asString(): string
    {
        if (false === $result = json_encode($this->value, $this->options, $this->depth)) {
            throw new JsonException(json_last_error_msg());
        }
        return $result;
    }
```

my solution here #5

**Comment by stepanets** [comment]
fixed
