### ISSUE TITLE
Shortcut functions

### ISSUE THREAD

**Issue by tigokr** [elegant-bro/stringify#22]
I think it would be great to do not write constantly `new Just(...)`

I propose to add `just` function with same sane - wrapping primitive type into elegant object
 Or it may be bit of magic function, which determines type of argument and apply to it proper just-wrapper

what do you think?

**Comment by stepanets** [comment]
You mean `new Formatted(just('%d apples'), 5);`? Well, it may be usefull, but I absolutely against any sort of type guessing like `instanceof`. But we can transform any scalar to `Just`, not only string: `just('5')` or `just(5)` or `just(5.5)`.

Another way we can add static constructor `Just::fromRaw('John')` or `Just::raw('The Coder')`. Or we can add `raw` method to any our objects - `Formatted::raw('%d apples', 5);`.

But it doesn't looks elegant. Fucking piashpi...

**Comment by tigokr** [comment]
> You mean `new Formatted(just('%d apples'), 5);`? Well, it may be usefull, but I absolutely against any sort of type guessing like `instanceof`. But we can transform any scalar to `Just`, not only string: `just('5')` or `just(5)` or `just(5.5)`.

it's "elegant brain" diagnose =) but `just` function is most convenient approach i think

**Comment by stepanets** [comment]
```php
function just($scalar): Stringify // lol this is highlighter bug
{
    return new Just((string) $scalar);
}
```
