### ISSUE TITLE
Uuid v4

### ISSUE THREAD

**Issue by stepanets** [elegant-bro/stringify#7]
add Uuid object (without any dependencies)

**Comment by tigokr** [comment]
this ticket mean only one class?
what operations you think it should implement?

**Comment by stepanets** [comment]
Yes, this one class should be uuid version 4, and can be represented as string. I think, once this object was created it must represent only one uuid. E.g. every time you ask `asString` you get the same value. If you want another random uuid - just create new instance.

**Comment by tigokr** [comment]
i found a solution for generating https://stackoverflow.com/questions/2040240/php-function-to-generate-v4-uuid
```php
function gen_uuid() {
    return sprintf( '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
        // 32 bits for "time_low"
        mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ),

        // 16 bits for "time_mid"
        mt_rand( 0, 0xffff ),

        // 16 bits for "time_hi_and_version",
        // four most significant bits holds version number 4
        mt_rand( 0, 0x0fff ) | 0x4000,

        // 16 bits, 8 bits for "clk_seq_hi_res",
        // 8 bits for "clk_seq_low",
        // two most significant bits holds zero and one for variant DCE1.1
        mt_rand( 0, 0x3fff ) | 0x8000,

        // 48 bits for "node"
        mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff )
    );
}
```
`fromString` constructor must do a bit validation of significant bits

**Comment by stepanets** [comment]
it really works!

**Comment by stepanets** [comment]
we do not need constructors from string for uuid v4, this this only random
