### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by stepanets** [elegant-bro/stringify#9]
Write about using stringify

**Comment by stepanets** [comment]
@tigokr @DrBallMD hey bro, comment [updated readme](https://github.com/elegant-bro/stringify/blob/%239_readme/README.md) please

**Comment by tigokr** [comment]
why update query in created in strange order?
i think it should be like 
UpdateQuery(What(Table, Join(Table, Predicate)), How(Set(),...), Where(Predicate(),...))
or similary with equal order to native sql query

**Comment by stepanets** [comment]
> 
> 
> why update query in created in strange order?
> i think it should be like
> UpdateQuery(What(Table, Join(Table, Predicate)), How(Set(),...), Where(Predicate(),...))
> or similary with equal order to native sql query

I don't invent Query component, it's just example of using Stringify.
What about common guideline?

**Comment by stepanets** [comment]
merged
